export const STOCKS = [
  { value: 'AAPL', label: 'Apple Inc.' },
  { value: 'MSFT', label: 'Microsoft Corporation' },
  { value: 'GOOGL', label: 'Alphabet Inc. Class A' },
  { value: 'GOOG', label: 'Alphabet Inc. Class C' },
  { value: 'AMZN', label: 'Amazon.com, Inc.' },
  { value: 'NVDA', label: 'NVIDIA Corporation' },
  { value: 'TSLA', label: 'Tesla, Inc.' },
  { value: 'META', label: 'Meta Platforms, Inc.' },
  { value: 'BRK.B', label: 'Berkshire Hathaway Inc. Class B' },
  { value: 'JPM', label: 'JPMorgan Chase & Co.' },
  { value: 'JNJ', label: 'Johnson & Johnson' },
  { value: 'V', label: 'Visa Inc.' },
  { value: 'PG', label: 'Procter & Gamble Company' },
  { value: 'UNH', label: 'UnitedHealth Group Incorporated' },
  { value: 'HD', label: 'The Home Depot, Inc.' },
  { value: 'MA', label: 'Mastercard Incorporated' },
  { value: 'BAC', label: 'Bank of America Corporation' },
  { value: 'PFE', label: 'Pfizer Inc.' },
  { value: 'XOM', label: 'Exxon Mobil Corporation' },
  { value: 'DIS', label: 'The Walt Disney Company' },
  { value: 'AVGO', label: 'Broadcom Inc.' },
  { value: 'CSCO', label: 'Cisco Systems, Inc.' },
  { value: 'LLY', label: 'Eli Lilly and Company' },
  { value: 'CVX', label: 'Chevron Corporation' },
  { value: 'PEP', label: 'PepsiCo, Inc.' },
  { value: 'KO', label: 'The Coca-Cola Company' },
  { value: 'ADBE', label: 'Adobe Inc.' },
  { value: 'WMT', label: 'Walmart Inc.' },
  { value: 'CRM', label: 'Salesforce, Inc.' },
  { value: 'NFLX', label: 'Netflix, Inc.' },
];
